version: '3.8'

services:
  fastapi-app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@127.0.0.1:5432/urlshortener
      - REDIS_URL=redis://127.0.0.1:6379/0
      
